const CHANGE_DRAWER = 'CHANGE_DRAWER';
const SAVE_TOKEN = 'SAVE_TOKEN';
const SAVE_PHONE = 'SAVE_PHONE';
const SAVE_CITIES = 'SAVE_CITIES';
const SAVE_CURRENT_DRAWER = 'SAVE_CURRENT_DRAWER';
const IS_DRIVER = 'IS_DRIVER';
const SAVE_CURRENT_USER_INFO = 'SAVE_CURRENT_USER_INFO';

export {
  CHANGE_DRAWER,
  SAVE_TOKEN,
  SAVE_PHONE,
  SAVE_CITIES,
  SAVE_CURRENT_DRAWER,
  IS_DRIVER,
  SAVE_CURRENT_USER_INFO,
};
